# Generated by Django 6.0.3 on 2026-03-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_ingredients_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='uploaded_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='step',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
