# Generated by Django 6.0.3 on 2026-03-06 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_uploaded_at_recipe_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['order'], 'verbose_name': 'Шаг', 'verbose_name_plural': 'Шаги'},
        ),
    ]
