# Generated by Django 6.0.3 on 2026-03-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_ingredient_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'name'), name='unique_recipe_ingredient'),
        ),
    ]
