"""
Django settings for RecipeAPI project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config     # Читаем переменные из .env
from datetime import timedelta  # Задаём срок жизни JWT-токенов
import dj_database_url          # Подключаем для настройки базы данных через URL
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')  # Берём SECRET_KEY из .env

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)  # Берём DEBUG из .env, если его нет - ставим False, приводим к
                                                   # булевому типу

ALLOWED_HOSTS = config('ALLOWED_HOSTS',
                       default='localhost,127.0.0.1,recipeapi.up.railway.app'
                       ).split(',')  # Берём разрешённые хосты из .env и преобразуем в список

# Настройки безопасности для продакшена
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # Сообщает Django, что запрос был HTTPS до прокси (Railway)

    SECURE_SSL_REDIRECT = True                  # Автоматически перенаправляет все HTTP-запросы на HTTPS
    SESSION_COOKIE_SECURE = True                # Делает cookie сессий доступными только по HTTPS
    CSRF_COOKIE_SECURE = True                   # То же самое для CSRF cookie
    SECURE_BROWSER_XSS_FILTER = True            # Включает встроенный фильтр XSS в браузерах
    SECURE_CONTENT_TYPE_NOSNIFF = True          # Запрещает браузеру угадывать тип контента
    X_FRAME_OPTIONS = 'DENY'                    # Запрещает вставку сайта в iframe

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Сторонние библиотеки
    'rest_framework',            # Для создания API
    'rest_framework_simplejwt',  # Для JWT-аутентификации
    'corsheaders',               # Для поддержки CORS
    'drf_yasg',                  # Для генерации документации Swagger

    # Локальные
    'recipes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Для поддержки CORS (разрешение запросов с других доменов/портов)
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'RecipeAPI.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': []  # Пустой список означает, что общие шаблоны проекта не используются
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',  # Для отладки шаблонов
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'RecipeAPI.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if DEBUG:
    # локальная база PostgreSQL
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',                    # Используем PostgreSQL
            'NAME': config('DATABASE_NAME', default='recipe_db'),         # \
            'USER': config('DATABASE_USER', default='postgres'),          #  \
            'PASSWORD': config('DATABASE_PASSWORD', default='postgres'),  #   - Берём все переменные из .env
            'HOST': config('DATABASE_HOST', default='localhost'),         #  / локалка = localhost, контейнер = db
            'PORT': config('DATABASE_PORT', default='5432'),              # /
        }
    }
# Настройка базы данных для Railway
# Если в окружении есть переменная DATABASE_URL, используем её для подключения к PostgreSQL
else:
    # продакшен через DATABASE_URL
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),  # берем URL из .env
            conn_max_age=600,
            conn_health_checks=True
        )
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'
TIME_ZONE = 'Europe/Moscow'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Для статических файлов
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Создаём папку, куда собираются все статические файлы командой collectstatic
                                        # (для продакшена, чтобы веб-сервер мог раздавать их напрямую)

# Для разработки: берём статику прямо из проекта
if DEBUG:
    STATICFILES_DIRS = [BASE_DIR / 'static']

# Для продакшена: использование WhiteNoise для раздачи статических файлов
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    WHITENOISE_USE_FINDERS = True

# Для медиафайлов (загрузка пользователями)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'  # Создаём папку, куда сохраняются загруженные пользователями файлы

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'  # По умолчанию будет создаваться первичный ключ для новых моделей

# Настройка Django REST Framework для работы с API
REST_FRAMEWORK = {
    # Как пользователи будут аутентифицироваться
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # Используем JWT-токены
    ],
    # Разрешения на доступ к API
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',  # Неавторизованные пользователи могут только читать
    ],
    # Пагинация
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',  # Нумерация страниц
    'PAGE_SIZE': 10,  # На одной странице будет 10 объектов
}

# JWT-аутентификация (JSON Web Tokens)
SIMPLE_JWT = {
    # Сколько будет жить access-токен (для запросов к API)
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # 1 час

    # Сколько будет жить refresh-токен (для обновления access-токена без повторного входа)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # 7 дней

    # Нужно ли менять refresh-токен каждый раз при обновлении access-токена
    'ROTATE_REFRESH_TOKENS': False,  # False - refresh-токен остаётся прежним

    # Добавлять старые refresh-токены в черный список после обновления
    'BLACKLIST_AFTER_ROTATION': True,  # True - блокируем старые refresh-токены
}

# Настройка Swagger для поддержки JWT-токенов. Позволяет в интерфейсе Swagger вставлять токен в поле "Authorize" и
# автоматически добавлять заголовок Authorization: Bearer <token> к запросам
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'USE_SESSION_AUTH': False,  # Убирает форму username/password
}
SWAGGER_USE_COMPAT_RENDERERS = False  # Убирает warning от drf-yasg при рендеринге документации

# CORS (разрешение запросов с других доменов/портов)
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = [
        'https://recipeapi.up.railway.app',
    ]